version: '3.7'
services:
  php:
    build: ./php
    ports:
    - 8080:8000
    volumes:
    - ./work:/work
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=my_db
    - MYSQL_USER=docker
    - MYSQL_PASSWORD=docker
    - TZ=Asia/Tokyo
  db:
    image: mysql:8.0
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=my_db
    - MYSQL_USER=docker
    - MYSQL_PASSWORD=docker
    - TZ=Asia/Tokyo
